### ISSUE TITLE
Defer the apt-get operations to config-changed hook

### ISSUE THREAD

**Issue by mbruzek** [whitmo/charm-kubernetes-master#10]
The gsutil command brings along with it an 'apt-get update', and 'apt-get install' of many packages.  Currently this happens in the install hook.  But we could optimize the install to avoid those operations until after config-changed checks to see if tar does not exist.  This would involve a bit of refactoring but the benefit would be faster installs when users are using the version of kubernetes that is in the charm.

**Comment by lazypower** [comment]
Is this still applicable considering we are now working against compiling from source?

**Comment by mbruzek** [comment]
No this issue is no longer needed the charm no longer uses gsutil.
